#!/usr/bin/env python3
# Generates src/ops.zig from QBE's ops.h (the C X-macro table).
import re, sys
src = open(sys.argv[1]).read()
pat = re.compile(r'^O\((\w+),\s*T\(([^)]*)\),\s*F\(([^)]*)\)\)\s*X\(([^)]*)\)\s*V\(([^)]*)\)', re.M)
rows = pat.findall(src)
out = ["// Generated by tools/gen_ops.py from ops.h -- do not edit.",
       "",
       "pub const OpDef = struct {",
       "    name: [:0]const u8,",
       "    /// argcls letters: [arg][Kw,Kl,Ks,Kd] in {w,l,s,d,m,x,e}",
       "    t: [2][4]u8,",
       "    /// canfold hasid idval commutes assoc idemp cmpeqwl cmplgtewl eqval pinned",
       "    f: [10]u1,",
       "    /// amd64: NMemArgs SetsZeroFlag LeavesFlags",
       "    x: [3]u8,",
       "    /// rv64: Imm",
       "    v: u1,",
       "};",
       "",
       "pub const Oxxx = 0;"]
for i,(n,_,_,_,_) in enumerate(rows):
    out.append(f"pub const O{n} = {i+1};")
out.append(f"pub const NOp = {len(rows)+1};")
out.append("")
out.append("pub const defs = [_]OpDef{")
for n,t,f,x,v in rows:
    t = [s.strip() for s in t.split(',')]
    f = [s.strip() for s in f.split(',')]
    x = [s.strip() for s in x.split(',')]
    ta = "'" + "', '".join(t[:4]) + "'"
    tb = "'" + "', '".join(t[4:]) + "'"
    out.append(f'    .{{ .name = "{n}", .t = .{{ .{{ {ta} }}, .{{ {tb} }} }}, .f = .{{ {", ".join(f)} }}, .x = .{{ {", ".join(x)} }}, .v = {v.strip()} }},')
out.append("};")
open(sys.argv[2],'w').write("\n".join(out)+"\n")
