#!/usr/bin/env python3
# Generates src/ops.zig from QBE's ops.h (the C X-macro table).
import re, sys
src = open(sys.argv[1]).read()
pat = re.compile(r'^O\((\w+),\s*T\(([^)]*)\),\s*F\(([^)]*)\)\)\s*X\(([^)]*)\)\s*V\(([^)]*)\)', re.M)
rows = pat.findall(src)
out = ["// Generated by tools/gen_ops.py from ops.h -- do not edit.",
       "",
       "pub const OpDef = struct {",
       "    name: [:0]const u8,",
       "    /// argcls letters: [arg][Kw,Kl,Ks,Kd] in {w,l,s,d,m,x,e}",
       "    t: [2][4]u8,",
       "    /// canfold hasid idval commutes assoc idemp cmpeqwl cmplgtewl eqval pinned",
       "    f: [10]u1,",
       "    /// amd64: NMemArgs SetsZeroFlag LeavesFlags",
       "    x: [3]u8,",
       "    /// rv64: Imm",
       "    v: u1,",
       "};",
       ""]
KW = {'addrspace','align','allowzero','and','anyframe','anytype','asm','break','callconv','catch','comptime','const','continue','defer','else','enum','errdefer','error','export','extern','fn','for','if','inline','noalias','noinline','nosuspend','opaque','or','orelse','packed','pub','resume','return','linksection','struct','suspend','switch','test','threadlocal','try','union','unreachable','var','volatile','while'}
def q(n):
    return '@"%s"' % n if n in KW else n
names = ['xxx'] + [r[0] for r in rows]
out.append("pub const Opc = enum(u32) {")
out += [f"    {q(n)}," for n in names]
out += ["",
        "    /// offset into the op numbers, e.g. `Opc.storeb.offset(k)` (C: Ostoreb + k)",
        "    pub inline fn offset(o: Opc, n: anytype) Opc {",
        "        return @enumFromInt(@as(i64, @intFromEnum(o)) + @as(i64, if (@typeInfo(@TypeOf(n)) == .@\"enum\") @intFromEnum(n) else @intCast(n)));",
        "    }",
        "    /// distance from another op (C: o - base)",
        "    pub inline fn diff(o: Opc, base: Opc) i32 {",
        "        return @as(i32, @intCast(@intFromEnum(o))) - @as(i32, @intCast(@intFromEnum(base)));",
        "    }",
        "    pub inline fn int(o: Opc) u32 {",
        "        return @intFromEnum(o);",
        "    }",
        "};"]
out += [f"pub const O{n} = Opc.{q(n)};" for n in names]
out += ["",
        "/// Accept an op given as `Opc` or as an integer (ported C code mixes both).",
        "pub inline fn of(x: anytype) Opc {",
        "    return if (@TypeOf(x) == Opc) x else @enumFromInt(@as(u32, @intCast(x)));",
        "}",
        "/// Op number of an `Opc` or integer.",
        "pub inline fn num(x: anytype) i32 {",
        "    return if (@TypeOf(x) == Opc) @intCast(@intFromEnum(x)) else @intCast(x);",
        "}",]
out.append(f"pub const NOp = {len(rows)+1};")
out.append("")
out.append("pub const defs = [_]OpDef{")
for n,t,f,x,v in rows:
    t = [s.strip() for s in t.split(',')]
    f = [s.strip() for s in f.split(',')]
    x = [s.strip() for s in x.split(',')]
    ta = "'" + "', '".join(t[:4]) + "'"
    tb = "'" + "', '".join(t[4:]) + "'"
    out.append(f'    .{{ .name = "{n}", .t = .{{ .{{ {ta} }}, .{{ {tb} }} }}, .f = .{{ {", ".join(f)} }}, .x = .{{ {", ".join(x)} }}, .v = {v.strip()} }},')
out.append("};")
open(sys.argv[2],'w').write("\n".join(out)+"\n")
