// Generated by tools/gen_ops.py from ops.h -- do not edit.

pub const OpDef = struct {
    name: [:0]const u8,
    /// argcls letters: [arg][Kw,Kl,Ks,Kd] in {w,l,s,d,m,x,e}
    t: [2][4]u8,
    /// canfold hasid idval commutes assoc idemp cmpeqwl cmplgtewl eqval pinned
    f: [10]u1,
    /// amd64: NMemArgs SetsZeroFlag LeavesFlags
    x: [3]u8,
    /// rv64: Imm
    v: u1,
};

pub const Opc = enum(u32) {
    xxx,
    add,
    sub,
    neg,
    div,
    rem,
    udiv,
    urem,
    mul,
    @"and",
    @"or",
    xor,
    sar,
    shr,
    shl,
    ceqw,
    cnew,
    csgew,
    csgtw,
    cslew,
    csltw,
    cugew,
    cugtw,
    culew,
    cultw,
    ceql,
    cnel,
    csgel,
    csgtl,
    cslel,
    csltl,
    cugel,
    cugtl,
    culel,
    cultl,
    ceqs,
    cges,
    cgts,
    cles,
    clts,
    cnes,
    cos,
    cuos,
    ceqd,
    cged,
    cgtd,
    cled,
    cltd,
    cned,
    cod,
    cuod,
    storeb,
    storeh,
    storew,
    storel,
    stores,
    stored,
    loadsb,
    loadub,
    loadsh,
    loaduh,
    loadsw,
    loaduw,
    load,
    extsb,
    extub,
    extsh,
    extuh,
    extsw,
    extuw,
    exts,
    truncd,
    stosi,
    stoui,
    dtosi,
    dtoui,
    swtof,
    uwtof,
    sltof,
    ultof,
    cast,
    alloc4,
    alloc8,
    alloc16,
    vaarg,
    vastart,
    copy,
    dbgloc,
    nop,
    addr,
    blit0,
    blit1,
    sel0,
    sel1,
    swap,
    sign,
    salloc,
    xidiv,
    xdiv,
    xcmp,
    xtest,
    acmp,
    acmn,
    afcmp,
    reqz,
    rnez,
    par,
    parsb,
    parub,
    parsh,
    paruh,
    parc,
    pare,
    arg,
    argsb,
    argub,
    argsh,
    arguh,
    argc,
    arge,
    argv,
    call,
    flagieq,
    flagine,
    flagisge,
    flagisgt,
    flagisle,
    flagislt,
    flagiuge,
    flagiugt,
    flagiule,
    flagiult,
    flagfeq,
    flagfge,
    flagfgt,
    flagfle,
    flagflt,
    flagfne,
    flagfo,
    flagfuo,
    xselieq,
    xseline,
    xselisge,
    xselisgt,
    xselisle,
    xselislt,
    xseliuge,
    xseliugt,
    xseliule,
    xseliult,
    xselfeq,
    xselfge,
    xselfgt,
    xselfle,
    xselflt,
    xselfne,
    xselfo,
    xselfuo,

    /// offset into the op numbers, e.g. `Opc.storeb.offset(k)` (C: Ostoreb + k)
    pub inline fn offset(o: Opc, n: anytype) Opc {
        return @enumFromInt(@as(i64, @intFromEnum(o)) + @as(i64, @intCast(n)));
    }
    /// distance from another op (C: o - base)
    pub inline fn diff(o: Opc, base: Opc) i32 {
        return @as(i32, @intCast(@intFromEnum(o))) - @as(i32, @intCast(@intFromEnum(base)));
    }
    pub inline fn int(o: Opc) u32 {
        return @intFromEnum(o);
    }
};
pub const Oxxx = Opc.xxx;
pub const Oadd = Opc.add;
pub const Osub = Opc.sub;
pub const Oneg = Opc.neg;
pub const Odiv = Opc.div;
pub const Orem = Opc.rem;
pub const Oudiv = Opc.udiv;
pub const Ourem = Opc.urem;
pub const Omul = Opc.mul;
pub const Oand = Opc.@"and";
pub const Oor = Opc.@"or";
pub const Oxor = Opc.xor;
pub const Osar = Opc.sar;
pub const Oshr = Opc.shr;
pub const Oshl = Opc.shl;
pub const Oceqw = Opc.ceqw;
pub const Ocnew = Opc.cnew;
pub const Ocsgew = Opc.csgew;
pub const Ocsgtw = Opc.csgtw;
pub const Ocslew = Opc.cslew;
pub const Ocsltw = Opc.csltw;
pub const Ocugew = Opc.cugew;
pub const Ocugtw = Opc.cugtw;
pub const Oculew = Opc.culew;
pub const Ocultw = Opc.cultw;
pub const Oceql = Opc.ceql;
pub const Ocnel = Opc.cnel;
pub const Ocsgel = Opc.csgel;
pub const Ocsgtl = Opc.csgtl;
pub const Ocslel = Opc.cslel;
pub const Ocsltl = Opc.csltl;
pub const Ocugel = Opc.cugel;
pub const Ocugtl = Opc.cugtl;
pub const Oculel = Opc.culel;
pub const Ocultl = Opc.cultl;
pub const Oceqs = Opc.ceqs;
pub const Ocges = Opc.cges;
pub const Ocgts = Opc.cgts;
pub const Ocles = Opc.cles;
pub const Oclts = Opc.clts;
pub const Ocnes = Opc.cnes;
pub const Ocos = Opc.cos;
pub const Ocuos = Opc.cuos;
pub const Oceqd = Opc.ceqd;
pub const Ocged = Opc.cged;
pub const Ocgtd = Opc.cgtd;
pub const Ocled = Opc.cled;
pub const Ocltd = Opc.cltd;
pub const Ocned = Opc.cned;
pub const Ocod = Opc.cod;
pub const Ocuod = Opc.cuod;
pub const Ostoreb = Opc.storeb;
pub const Ostoreh = Opc.storeh;
pub const Ostorew = Opc.storew;
pub const Ostorel = Opc.storel;
pub const Ostores = Opc.stores;
pub const Ostored = Opc.stored;
pub const Oloadsb = Opc.loadsb;
pub const Oloadub = Opc.loadub;
pub const Oloadsh = Opc.loadsh;
pub const Oloaduh = Opc.loaduh;
pub const Oloadsw = Opc.loadsw;
pub const Oloaduw = Opc.loaduw;
pub const Oload = Opc.load;
pub const Oextsb = Opc.extsb;
pub const Oextub = Opc.extub;
pub const Oextsh = Opc.extsh;
pub const Oextuh = Opc.extuh;
pub const Oextsw = Opc.extsw;
pub const Oextuw = Opc.extuw;
pub const Oexts = Opc.exts;
pub const Otruncd = Opc.truncd;
pub const Ostosi = Opc.stosi;
pub const Ostoui = Opc.stoui;
pub const Odtosi = Opc.dtosi;
pub const Odtoui = Opc.dtoui;
pub const Oswtof = Opc.swtof;
pub const Ouwtof = Opc.uwtof;
pub const Osltof = Opc.sltof;
pub const Oultof = Opc.ultof;
pub const Ocast = Opc.cast;
pub const Oalloc4 = Opc.alloc4;
pub const Oalloc8 = Opc.alloc8;
pub const Oalloc16 = Opc.alloc16;
pub const Ovaarg = Opc.vaarg;
pub const Ovastart = Opc.vastart;
pub const Ocopy = Opc.copy;
pub const Odbgloc = Opc.dbgloc;
pub const Onop = Opc.nop;
pub const Oaddr = Opc.addr;
pub const Oblit0 = Opc.blit0;
pub const Oblit1 = Opc.blit1;
pub const Osel0 = Opc.sel0;
pub const Osel1 = Opc.sel1;
pub const Oswap = Opc.swap;
pub const Osign = Opc.sign;
pub const Osalloc = Opc.salloc;
pub const Oxidiv = Opc.xidiv;
pub const Oxdiv = Opc.xdiv;
pub const Oxcmp = Opc.xcmp;
pub const Oxtest = Opc.xtest;
pub const Oacmp = Opc.acmp;
pub const Oacmn = Opc.acmn;
pub const Oafcmp = Opc.afcmp;
pub const Oreqz = Opc.reqz;
pub const Ornez = Opc.rnez;
pub const Opar = Opc.par;
pub const Oparsb = Opc.parsb;
pub const Oparub = Opc.parub;
pub const Oparsh = Opc.parsh;
pub const Oparuh = Opc.paruh;
pub const Oparc = Opc.parc;
pub const Opare = Opc.pare;
pub const Oarg = Opc.arg;
pub const Oargsb = Opc.argsb;
pub const Oargub = Opc.argub;
pub const Oargsh = Opc.argsh;
pub const Oarguh = Opc.arguh;
pub const Oargc = Opc.argc;
pub const Oarge = Opc.arge;
pub const Oargv = Opc.argv;
pub const Ocall = Opc.call;
pub const Oflagieq = Opc.flagieq;
pub const Oflagine = Opc.flagine;
pub const Oflagisge = Opc.flagisge;
pub const Oflagisgt = Opc.flagisgt;
pub const Oflagisle = Opc.flagisle;
pub const Oflagislt = Opc.flagislt;
pub const Oflagiuge = Opc.flagiuge;
pub const Oflagiugt = Opc.flagiugt;
pub const Oflagiule = Opc.flagiule;
pub const Oflagiult = Opc.flagiult;
pub const Oflagfeq = Opc.flagfeq;
pub const Oflagfge = Opc.flagfge;
pub const Oflagfgt = Opc.flagfgt;
pub const Oflagfle = Opc.flagfle;
pub const Oflagflt = Opc.flagflt;
pub const Oflagfne = Opc.flagfne;
pub const Oflagfo = Opc.flagfo;
pub const Oflagfuo = Opc.flagfuo;
pub const Oxselieq = Opc.xselieq;
pub const Oxseline = Opc.xseline;
pub const Oxselisge = Opc.xselisge;
pub const Oxselisgt = Opc.xselisgt;
pub const Oxselisle = Opc.xselisle;
pub const Oxselislt = Opc.xselislt;
pub const Oxseliuge = Opc.xseliuge;
pub const Oxseliugt = Opc.xseliugt;
pub const Oxseliule = Opc.xseliule;
pub const Oxseliult = Opc.xseliult;
pub const Oxselfeq = Opc.xselfeq;
pub const Oxselfge = Opc.xselfge;
pub const Oxselfgt = Opc.xselfgt;
pub const Oxselfle = Opc.xselfle;
pub const Oxselflt = Opc.xselflt;
pub const Oxselfne = Opc.xselfne;
pub const Oxselfo = Opc.xselfo;
pub const Oxselfuo = Opc.xselfuo;

/// Accept an op given as `Opc` or as an integer (ported C code mixes both).
pub inline fn of(x: anytype) Opc {
    return if (@TypeOf(x) == Opc) x else @enumFromInt(@as(u32, @intCast(x)));
}
/// Op number of an `Opc` or integer.
pub inline fn num(x: anytype) i32 {
    return if (@TypeOf(x) == Opc) @intCast(@intFromEnum(x)) else @intCast(x);
}
pub const NOp = 158;

pub const defs = [_]OpDef{
    .{ .name = "add", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'w', 'l', 's', 'd' } }, .f = .{ 1, 1, 0, 1, 1, 0, 0, 0, 0, 0 }, .x = .{ 2, 1, 0 }, .v = 1 },
    .{ .name = "sub", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'w', 'l', 's', 'd' } }, .f = .{ 1, 1, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 2, 1, 0 }, .v = 0 },
    .{ .name = "neg", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 1, 0 }, .v = 0 },
    .{ .name = "div", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'w', 'l', 's', 'd' } }, .f = .{ 1, 1, 1, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "rem", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "udiv", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 1, 1, 1, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "urem", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "mul", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'w', 'l', 's', 'd' } }, .f = .{ 1, 1, 1, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 2, 0, 0 }, .v = 0 },
    .{ .name = "and", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 1, 1, 0, 0, 0, 0 }, .x = .{ 2, 1, 0 }, .v = 1 },
    .{ .name = "or", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 1, 1, 0, 1, 1, 1, 0, 0, 0, 0 }, .x = .{ 2, 1, 0 }, .v = 1 },
    .{ .name = "xor", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 1, 1, 0, 1, 1, 0, 0, 0, 0, 0 }, .x = .{ 2, 1, 0 }, .v = 1 },
    .{ .name = "sar", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 1, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 0, 0 }, .v = 1 },
    .{ .name = "shr", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 1, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 0, 0 }, .v = 1 },
    .{ .name = "shl", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 1, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 0, 0 }, .v = 1 },
    .{ .name = "ceqw", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 1, 1, 1, 0, 0, 1, 0, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cnew", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 1, 0, 1, 0, 0, 1, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "csgew", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "csgtw", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cslew", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "csltw", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 1 },
    .{ .name = "cugew", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cugtw", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "culew", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cultw", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'w', 'w', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 1 },
    .{ .name = "ceql", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 1, 0, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cnel", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 1, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "csgel", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "csgtl", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cslel", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "csltl", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 1 },
    .{ .name = "cugel", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cugtl", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "culel", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 1, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cultl", .t = .{ .{ 'l', 'l', 'e', 'e' }, .{ 'l', 'l', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 1 },
    .{ .name = "ceqs", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cges", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cgts", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cles", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "clts", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cnes", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cos", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cuos", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 's', 's', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "ceqd", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cged", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cgtd", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cled", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cltd", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cned", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cod", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "cuod", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'd', 'd', 'e', 'e' } }, .f = .{ 1, 0, 0, 1, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "storeb", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "storeh", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "storew", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "storel", .t = .{ .{ 'l', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "stores", .t = .{ .{ 's', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "stored", .t = .{ .{ 'd', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "loadsb", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "loadub", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "loadsh", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "loaduh", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "loadsw", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "loaduw", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "load", .t = .{ .{ 'm', 'm', 'm', 'm' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "extsb", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "extub", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "extsh", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "extuh", .t = .{ .{ 'w', 'w', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "extsw", .t = .{ .{ 'e', 'w', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "extuw", .t = .{ .{ 'e', 'w', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "exts", .t = .{ .{ 'e', 'e', 'e', 's' }, .{ 'e', 'e', 'e', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "truncd", .t = .{ .{ 'e', 'e', 'd', 'e' }, .{ 'e', 'e', 'x', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "stosi", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "stoui", .t = .{ .{ 's', 's', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "dtosi", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "dtoui", .t = .{ .{ 'd', 'd', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "swtof", .t = .{ .{ 'e', 'e', 'w', 'w' }, .{ 'e', 'e', 'x', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "uwtof", .t = .{ .{ 'e', 'e', 'w', 'w' }, .{ 'e', 'e', 'x', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "sltof", .t = .{ .{ 'e', 'e', 'l', 'l' }, .{ 'e', 'e', 'x', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "ultof", .t = .{ .{ 'e', 'e', 'l', 'l' }, .{ 'e', 'e', 'x', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "cast", .t = .{ .{ 's', 'd', 'w', 'l' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "alloc4", .t = .{ .{ 'e', 'l', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "alloc8", .t = .{ .{ 'e', 'l', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "alloc16", .t = .{ .{ 'e', 'l', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "vaarg", .t = .{ .{ 'm', 'm', 'm', 'm' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "vastart", .t = .{ .{ 'm', 'e', 'e', 'e' }, .{ 'x', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "copy", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "dbgloc", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'w', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "nop", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "addr", .t = .{ .{ 'm', 'm', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "blit0", .t = .{ .{ 'm', 'e', 'e', 'e' }, .{ 'm', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "blit1", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'x', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 1, 0 }, .v = 0 },
    .{ .name = "sel0", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'x', 'e', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "sel1", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "swap", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'w', 'l', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 0, 0 }, .v = 0 },
    .{ .name = "sign", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "salloc", .t = .{ .{ 'e', 'l', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xidiv", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 0, 0 }, .v = 0 },
    .{ .name = "xdiv", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 0, 0 }, .v = 0 },
    .{ .name = "xcmp", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'w', 'l', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 1, 0 }, .v = 0 },
    .{ .name = "xtest", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 1, 1, 0 }, .v = 0 },
    .{ .name = "acmp", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "acmn", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "afcmp", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "reqz", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "rnez", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "par", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "parsb", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "parub", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "parsh", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "paruh", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "parc", .t = .{ .{ 'e', 'x', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "pare", .t = .{ .{ 'e', 'x', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "arg", .t = .{ .{ 'w', 'l', 's', 'd' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "argsb", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "argub", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "argsh", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "arguh", .t = .{ .{ 'w', 'e', 'e', 'e' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "argc", .t = .{ .{ 'e', 'x', 'e', 'e' }, .{ 'e', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "arge", .t = .{ .{ 'e', 'l', 'e', 'e' }, .{ 'e', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "argv", .t = .{ .{ 'x', 'x', 'x', 'x' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "call", .t = .{ .{ 'm', 'm', 'm', 'm' }, .{ 'x', 'x', 'x', 'x' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "flagieq", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagine", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagisge", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagisgt", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagisle", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagislt", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagiuge", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagiugt", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagiule", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagiult", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfeq", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfge", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfgt", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfle", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagflt", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfne", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfo", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "flagfuo", .t = .{ .{ 'x', 'x', 'e', 'e' }, .{ 'x', 'x', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 1 }, .v = 0 },
    .{ .name = "xselieq", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xseline", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselisge", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselisgt", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselisle", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselislt", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xseliuge", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xseliugt", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xseliule", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xseliult", .t = .{ .{ 'w', 'l', 'e', 'e' }, .{ 'w', 'l', 'e', 'e' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfeq", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfge", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfgt", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfle", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselflt", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfne", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfo", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
    .{ .name = "xselfuo", .t = .{ .{ 'e', 'e', 's', 'd' }, .{ 'e', 'e', 's', 'd' } }, .f = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }, .x = .{ 0, 0, 0 }, .v = 0 },
};
